# Generated by Django 4.2.1 on 2023-08-15 23:40

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='branch_dept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'ordering': ['branch'],
            },
        ),
        migrations.CreateModel(
            name='Branches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(choices=[('LAGOS', 'LAGOS BRANCH'), ('IBADAN', 'IBADAN BRANCH'), ('PH', 'PH BRANCH'), ('ABUJA', 'ABUJA BRANCH'), ('ENUGU', 'ENUGU BRANCH')], max_length=20, unique=True)),
            ],
            options={
                'ordering': ['branch_name'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dep_name', models.CharField(choices=[('ADMIN', 'ADMIN DEPARTMENT'), ('IT', 'IT DEPARTMENT'), ('ACCOUNTS', 'ACCOUNT DEPARTMENT'), ('HR', 'HR DEPARTMENT'), ('SALES', 'SALES DEPARTMENT')], max_length=20, unique=True)),
            ],
            options={
                'ordering': ['dep_name'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dob', models.DateField(auto_created=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('salary', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.branch_dept')),
                ('user_name', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='company.profile')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.AddField(
            model_name='branch_dept',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.branches'),
        ),
        migrations.AddField(
            model_name='branch_dept',
            name='dept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.department'),
        ),
    ]
