# Generated by Django 4.2.1 on 2023-09-12 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0003_alter_post_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='profile',
            field=models.ImageField(upload_to='media/authors/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='upload_image',
            field=models.ImageField(upload_to='media/posts/'),
        ),
    ]
