# Generated by Django 4.2.1 on 2023-09-12 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0004_alter_author_profile_alter_post_upload_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='profile',
            field=models.ImageField(upload_to='authors/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='upload_image',
            field=models.ImageField(upload_to='posts/'),
        ),
    ]
