# Generated by Django 4.2.1 on 2023-09-23 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0005_alter_author_profile_alter_post_upload_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='about',
            field=models.TextField(default='I AM AN AUTHOR', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='author',
            name='profile',
            field=models.ImageField(upload_to='media/authors/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='upload_image',
            field=models.ImageField(upload_to='media/posts/'),
        ),
    ]
